public void testGetUserNameException() throws Exception {
    try {
        evilDAO.getUserName(0L);
        fail("DBException should have been thrown");
    } catch (DBException e) {
        assertEquals(EvilDAOFactory.MESSAGE, e.getSQLException().getMessage());
    }
}