public void testAddException() throws Exception {
    try {
        evilDAO.add(new OfficeVisitBean());
        fail("DBException should have been thrown");
    } catch (DBException e) {
        assertEquals(EvilDAOFactory.MESSAGE, e.getSQLException().getMessage());
    }
}