public void testDoesNotExist() throws Exception {
    try {
        personnelDAO.getName(0L);
        fail("exception should have been thrown");
    } catch (iTrustException e) {
        assertEquals("User does not exist", e.getMessage());
    }
}