public void testPatientAllErrors() throws Exception {
    MailValidator val = new MailValidator();
    PersonnelBean p = new PersonnelBean();
    p.setFirstName("Person5");
    p.setLastName("LastName5");
    p.setEmail("andy.programmer?gmail.com");
    try {
        new AddPersonnelValidator().validate(p);
        fail("exception should have been thrown");
    } catch (FormValidationException e) {
        assertEquals(("First name: " + (ValidationFormat.NAME.getDescription())), e.getErrorList().get(0));
        assertEquals(("Last name: " + (ValidationFormat.NAME.getDescription())), e.getErrorList().get(1));
        assertEquals(false, val.validateEmail("andy.programmer?gmail.com"));
        assertEquals("number of errors", 3, e.getErrorList().size());
    }
}